#include <nds.h>
#include "gl2d.h"
#include <maxmod9.h>

#include "graphics/fontHandler.h"
#include "graphics/graphics.h"

#include "sprite_player.h"

static bool playerDirection = true;
static bool animateLegs = false;
static int playerTexID, playerX, playerY, legAniFrame, legAniDelay;
static glImage playerImage[(128 / 16) * (16 / 16)];

void setPlayerPosition(int x, int y) {
	playerX = x;
	playerY = y;
}

void playerGraphicLoad(void) {
	playerTexID = glLoadTileSet(playerImage, // pointer to glImage array
							16, // sprite width
							16, // sprite height
							128, // bitmap width
							16, // bitmap height
							GL_RGB16, // texture type for glTexImage2D() in videoGL.h
							TEXTURE_SIZE_128, // sizeX for glTexImage2D() in videoGL.h
							TEXTURE_SIZE_16, // sizeY for glTexImage2D() in videoGL.h
							TEXGEN_OFF | GL_TEXTURE_COLOR0_TRANSPARENT, // param for glTexImage2D() in videoGL.h
							3, // Length of the palette to use (3 colors)
							(u16*) sprite_playerPal, // Load our 16 color tiles palette
							(u8*) sprite_playerBitmap // image data generated by GRIT
							);
}

void playerLoop(int pressed, int held) {
	if (held & KEY_LEFT) {
		playerDirection = false;
		playerX -= 1;
	} else if (held & KEY_RIGHT) {
		playerDirection = true;
		playerX += 1;
	}
	
	animateLegs = ((held & KEY_LEFT) || (held & KEY_RIGHT));
}

void renderPlayer(void) {
	glBoxFilled(playerX+2, playerY+2, playerX+8, playerY+6, RGB15(0, 31, 0));		// Eye color
	glColor(RGB15(219/8, 172/8, 129/8));											// Head color
	glSprite(playerX-3, playerY, playerDirection ? GL_FLIP_NONE : GL_FLIP_H, &playerImage[0]);						// Head
	glColor(RGB15(31, 31, 31));
	glSprite(playerX-3, playerY+9, playerDirection ? GL_FLIP_NONE : GL_FLIP_H, &playerImage[1]);					// Torso
	glSprite(playerX-3, playerY+17, playerDirection ? GL_FLIP_NONE : GL_FLIP_H, &playerImage[2+legAniFrame]);	// Legs

	if (animateLegs) {
		legAniDelay++;
		if (legAniDelay==3) {
			legAniFrame++;
			if (legAniFrame > 2) {
				legAniFrame = 0;
			}
			legAniDelay = 0;
		}
	} else {
		legAniFrame = 0;
		legAniDelay = 2;
	}
}
